# Generated by Django 4.1.3 on 2022-12-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavisapp', '0002_alter_hamakua_data_pitfalltrapnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamakua_data',
            name='pitfallTrapNum',
        ),
    ]
