# Generated by Django 4.1.3 on 2022-12-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavisapp', '0003_remove_hamakua_data_pitfalltrapnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamakua_data',
            old_name='taxonmicResolution',
            new_name='taxonomicResolution',
        ),
    ]
