# Generated by Django 4.1.3 on 2022-12-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisapp', '0004_rename_taxonmicresolution_hamakua_data_taxonomicresolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamakua_data',
            name='basin',
            field=models.CharField(max_length=999),
        ),
    ]
